name: mmdflow
channels:
  - pytorch
  - astra-toolbox
dependencies:
  - python=3.9.13
  - numpy=1.23.3
  - matplotlib=3.6.1
  - scikit-image=0.19.3
  - pytorch::pytorch=1.12.1
  - pytorch::torchvision=0.13.1
  - astra-toolbox::astra-toolbox=2.1.2
  - pip
  - pip:
    - dival==0.6.1
